<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="MAIN" Id="{45381f7c-4c5f-4ec8-9129-311fb837ab4d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[



(* Call all Programs*)
PRG_ILK();
PRG_DIFF_PUMP();
PRG_ROOTS();
PRG_GATT();
PRG_GEM();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="37" Count="9" />
      <LineId Id="29" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>